token:
  expiration_time: 12345678
  secret: dohyundevsecret

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: "{cipher}28a2cb3ab77911916b91b686172ddfebc375af159e64b04d420fd090932f7c85"
